version: '3.3'
volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file:
      - ../.env.example
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    env_file:
      - ../.env.example
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: foodgram-front
    build: ../frontend
    env_file:
      - ../.env.example
    command: cp -r /app/build/ /frontend_static/
    volumes:
      - static:/frontend_static
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    env_file:
      - ../.env.example
    ports:
      - 8000:80
    volumes:
      - static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/  
    depends_on:
      - backend
