# Generated by Django 3.2 on 2024-12-26 19:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(help_text='Введите время в минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='recipes_media/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipesIngredients', to='recipes.Ingredients', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='short_link',
            field=models.TextField(blank=True, verbose_name='Короткая ссылка'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(through='recipes.RecipesTags', to='recipes.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='amount',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
