# Generated by Django 3.2 on 2024-11-24 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 28, 5, 498771)),
        ),
    ]
