# Generated by Django 3.2 on 2024-12-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20241226_2205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipesingredients',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='recipestags',
            unique_together={('recipe', 'tag')},
        ),
    ]
