# Generated by Django 3.2 on 2024-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20241217_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.TextField(max_length=256, verbose_name='Название'),
        ),
    ]
