# Generated by Django 3.2 on 2024-11-24 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20241124_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 42, 30, 514044)),
        ),
    ]
