# Generated by Django 3.2 on 2024-12-28 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20241228_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.TextField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Введите время в минутах', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректное имя.', regex='^[\\w.@+-]+$')]),
        ),
    ]
