# Generated by Django 3.2 on 2024-12-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcard',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_is_shopping', to='recipes.recipes'),
        ),
    ]
