# Generated by Django 3.2 on 2024-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_shoppingcard_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.TextField(max_length=256, unique=True, verbose_name='Название'),
        ),
    ]
