# Generated by Django 3.2 on 2024-11-26 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20241124_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='short_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 11, 35, 4, 750712)),
        ),
    ]
