# Generated by Django 3.2 on 2024-12-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20241228_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipes.RecipesIngredients', to='recipes.Ingredients', verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(blank=True, through='recipes.RecipesTags', to='recipes.Tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
