# Generated by Django 3.2 on 2024-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.TextField(max_length=256, verbose_name='Название'),
        ),
    ]
