# Generated by Django 3.2 on 2024-12-02 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipes_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 20, 53, 20, 457064)),
        ),
    ]
