# Generated by Django 3.2 on 2024-11-24 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректное имя.', regex='^[\\w.@+-]+$')]),
        ),
    ]
