# Generated by Django 3.2 on 2024-12-28 13:19

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelManagers(
            name='customusers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='role',
        ),
        migrations.AlterUniqueTogether(
            name='subscribers',
            unique_together={('author', 'subscriber')},
        ),
    ]
