# Generated by Django 3.2 on 2024-12-28 14:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241228_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users_media/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='first_name',
            field=models.TextField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='last_name',
            field=models.TextField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.TextField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введите корректное имя.', regex='^[\\w.@+-]+$')], verbose_name='Пользовательское имя'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
